const data = {
	products: [
		{
			_id: '1',
			name: 'Smart phones',
			slug: 'galaxy-smart-phones',
			catagory: 'phones',
			image: '/Assets/smartPhone.png',
			price: '5000SEK',
			countInStock: 0,
			brand: 'Samsung',
			rating: 4.5,
			numReviews: 10,
			descriptioin: 'hight quality HD camera',
		},
		{
			_id: '2',
			name: 'Smart phones',
			slug: 'tv-smart',
			catagory: 'phones',
			image: '/Assets/tv.png',
			price: '5000SEK',
			countInStock: 10,
			brand: 'Samsung',
			rating: 4.5,
			numReviews: 10,
			descriptioin: 'hight quality HD camera',
		},
		{
			_id: '3',
			name: 'Smart phones',
			slug: 'laptop',
			catagory: 'laptop',
			image: '/Assets/p1.png',
			price: '5000SEK',
			countInStock: 10,
			brand: 'Samsung',
			rating: 4.5,
			numReviews: 10,
			descriptioin: 'hight quality HD camera',
		},
		{
			_id: '4',
			name: 'Smart phones',
			slug: 'camera-smart',
			catagory: 'phones',
			image: '/Assets/camera.png',
			price: '5000SEK',
			countInStock: 10,
			brand: 'Samsung',
			rating: 4.5,
			numReviews: 10,
			descriptioin: 'hight quality HD camera',
		},
	],
};

export default data;
